#include "test_stack_operations.h"
#include "test_stack_index.h"
#include "test_sort_operations.h"
//#include "test_markup.h"
//#include "test_sort_operation_fill_b.h"
//#include "test_misc_functions.h"
//#include "test_move_b_back_to_a.h"
#include "test_integration.h"